config/routes.rb
Rails.application.routes.draw do
  resources :books

  resources :fees

  resources :order_details

  resources :orders

  resources :sale_details

  resources :sales

  resources :promotions

  resources :providers

  resources :clients

   root 'books#index'

end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
end

app/controllers/order_details_controller.rb
class OrderDetailsController < ApplicationController
  before_action :set_order_detail, only: [:show, :edit, :update, :destroy]

  # GET /order_details
  # GET /order_details.json
  def index
    @order_details = OrderDetail.all
  end

  # GET /order_details/1
  # GET /order_details/1.json
  def show
  end

  # GET /order_details/new
  def new
    @order_detail = OrderDetail.new
  end

  # GET /order_details/1/edit
  def edit
  end

  # POST /order_details
  # POST /order_details.json
  def create
    @order_detail = OrderDetail.new(order_detail_params)

    respond_to do |format|
      if @order_detail.save
        format.html { redirect_to @order_detail, notice: 'Order detail was successfully created.' }
        format.json { render :show, status: :created, location: @order_detail }
      else
        format.html { render :new }
        format.json { render json: @order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_details/1
  # PATCH/PUT /order_details/1.json
  def update
    respond_to do |format|
      if @order_detail.update(order_detail_params)
        format.html { redirect_to @order_detail, notice: 'Order detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_detail }
      else
        format.html { render :edit }
        format.json { render json: @order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_details/1
  # DELETE /order_details/1.json
  def destroy
    @order_detail.destroy
    respond_to do |format|
      format.html { redirect_to order_details_url, notice: 'Order detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_detail
      @order_detail = OrderDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_detail_params
      params.require(:order_detail).permit(:book_id, :order_id, :cantidad, :descuento, :preciouni, :cantidadtotal, :importe)
    end
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/views/order_details/_form.html.erb
<%= form_for(@order_detail) do |f| %>
  <% if @order_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_detail.errors.count, "error") %> prohibited this order_detail from being saved:</h2>

      <ul>
      <% @order_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_id %><br>
    <%= f.number_field :book_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :descuento %><br>
    <%= f.text_field :descuento %>
  </div>
  <div class="field">
    <%= f.label :preciouni %><br>
    <%= f.text_field :preciouni %>
  </div>
  <div class="field">
    <%= f.label :cantidadtotal %><br>
    <%= f.text_field :cantidadtotal %>
  </div>
  <div class="field">
    <%= f.label :importe %><br>
    <%= f.text_field :importe %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_details/edit.html.erb
<h1>Editing order_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_detail %> |
<%= link_to 'Back', order_details_path %>

app/views/order_details/index.html.erb
<h1>Listing order_details</h1>

<table>
  <thead>
    <tr>
      <th>Book</th>
      <th>Order</th>
      <th>Cantidad</th>
      <th>Descuento</th>
      <th>Preciouni</th>
      <th>Cantidadtotal</th>
      <th>Importe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_details.each do |order_detail| %>
      <tr>
        <td><%= order_detail.book_id %></td>
        <td><%= order_detail.order_id %></td>
        <td><%= order_detail.cantidad %></td>
        <td><%= order_detail.descuento %></td>
        <td><%= order_detail.preciouni %></td>
        <td><%= order_detail.cantidadtotal %></td>
        <td><%= order_detail.importe %></td>
        <td><%= link_to 'Show', order_detail %></td>
        <td><%= link_to 'Edit', edit_order_detail_path(order_detail) %></td>
        <td><%= link_to 'Destroy', order_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order detail', new_order_detail_path %>

app/views/order_details/new.html.erb
<h1>New order_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', order_details_path %>

app/views/order_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @order_detail.book_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_detail.order_id %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @order_detail.cantidad %>
</p>

<p>
  <strong>Descuento:</strong>
  <%= @order_detail.descuento %>
</p>

<p>
  <strong>Preciouni:</strong>
  <%= @order_detail.preciouni %>
</p>

<p>
  <strong>Cantidadtotal:</strong>
  <%= @order_detail.cantidadtotal %>
</p>

<p>
  <strong>Importe:</strong>
  <%= @order_detail.importe %>
</p>

<%= link_to 'Edit', edit_order_detail_path(@order_detail) %> |
<%= link_to 'Back', order_details_path %>