config/routes.rb
Rails.application.routes.draw do
  resources :books

  resources :fees

  resources :order_details

  resources :orders

  resources :sale_details

  resources :sales

  resources :promotions

  resources :providers

  resources :clients

   root 'books#index'

end

app/models/sale_detail.rb
class SaleDetail < ActiveRecord::Base
end

app/controllers/sale_details_controller.rb
class SaleDetailsController < ApplicationController
  before_action :set_sale_detail, only: [:show, :edit, :update, :destroy]

  # GET /sale_details
  # GET /sale_details.json
  def index
    @sale_details = SaleDetail.all
  end

  # GET /sale_details/1
  # GET /sale_details/1.json
  def show
  end

  # GET /sale_details/new
  def new
    @sale_detail = SaleDetail.new
  end

  # GET /sale_details/1/edit
  def edit
  end

  # POST /sale_details
  # POST /sale_details.json
  def create
    @sale_detail = SaleDetail.new(sale_detail_params)

    respond_to do |format|
      if @sale_detail.save
        format.html { redirect_to @sale_detail, notice: 'Sale detail was successfully created.' }
        format.json { render :show, status: :created, location: @sale_detail }
      else
        format.html { render :new }
        format.json { render json: @sale_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sale_details/1
  # PATCH/PUT /sale_details/1.json
  def update
    respond_to do |format|
      if @sale_detail.update(sale_detail_params)
        format.html { redirect_to @sale_detail, notice: 'Sale detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale_detail }
      else
        format.html { render :edit }
        format.json { render json: @sale_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sale_details/1
  # DELETE /sale_details/1.json
  def destroy
    @sale_detail.destroy
    respond_to do |format|
      format.html { redirect_to sale_details_url, notice: 'Sale detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale_detail
      @sale_detail = SaleDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_detail_params
      params.require(:sale_detail).permit(:sale_id, :book_id, :preciouni, :cantidad, :importe, :descuento)
    end
end

app/helpers/sale_details_helper.rb
module SaleDetailsHelper
end

app/views/sale_details/_form.html.erb
<%= form_for(@sale_detail) do |f| %>
  <% if @sale_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale_detail.errors.count, "error") %> prohibited this sale_detail from being saved:</h2>

      <ul>
      <% @sale_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sale_id %><br>
    <%= f.number_field :sale_id %>
  </div>
  <div class="field">
    <%= f.label :book_id %><br>
    <%= f.number_field :book_id %>
  </div>
  <div class="field">
    <%= f.label :preciouni %><br>
    <%= f.text_field :preciouni %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :importe %><br>
    <%= f.text_field :importe %>
  </div>
  <div class="field">
    <%= f.label :descuento %><br>
    <%= f.text_field :descuento %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sale_details/edit.html.erb
<h1>Editing sale_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale_detail %> |
<%= link_to 'Back', sale_details_path %>

app/views/sale_details/index.html.erb
<h1>Listing sale_details</h1>

<table>
  <thead>
    <tr>
      <th>Sale</th>
      <th>Book</th>
      <th>Preciouni</th>
      <th>Cantidad</th>
      <th>Importe</th>
      <th>Descuento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sale_details.each do |sale_detail| %>
      <tr>
        <td><%= sale_detail.sale_id %></td>
        <td><%= sale_detail.book_id %></td>
        <td><%= sale_detail.preciouni %></td>
        <td><%= sale_detail.cantidad %></td>
        <td><%= sale_detail.importe %></td>
        <td><%= sale_detail.descuento %></td>
        <td><%= link_to 'Show', sale_detail %></td>
        <td><%= link_to 'Edit', edit_sale_detail_path(sale_detail) %></td>
        <td><%= link_to 'Destroy', sale_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale detail', new_sale_detail_path %>

app/views/sale_details/new.html.erb
<h1>New sale_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', sale_details_path %>

app/views/sale_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sale:</strong>
  <%= @sale_detail.sale_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @sale_detail.book_id %>
</p>

<p>
  <strong>Preciouni:</strong>
  <%= @sale_detail.preciouni %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @sale_detail.cantidad %>
</p>

<p>
  <strong>Importe:</strong>
  <%= @sale_detail.importe %>
</p>

<p>
  <strong>Descuento:</strong>
  <%= @sale_detail.descuento %>
</p>

<%= link_to 'Edit', edit_sale_detail_path(@sale_detail) %> |
<%= link_to 'Back', sale_details_path %>